# Generated by Django 5.2.10 on 2026-01-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='allowance',
        ),
        migrations.AddField(
            model_name='salary',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
