# Generated by Django 5.2.10 on 2026-01-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_remove_salary_allowance_salary_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
